### PR TITLE
Version 3.4 enable default

### PR DESCRIPTION
**Pull request by akaryakinx**
There are two changes in this PR:
-- flow info is enabled by default in the source code. Otherwise, enabling it in OpenWRT is a pain. You either have to use insmod with a parameter (ndpi_enable_flow=1), or add this parameter to /etc/modules.d.ipt-ndpi and reload the module or reboot. Parameters in the modprobe command are ignored! There is no provision in the OpeWRT build system to specify module parameters. I would be happy to remove this patch if there are objections.
-- upstream version is bumped to 3.4. There is some work is being done on 3.5, but it has not been tagged. This fixes the "Unknown symbol __aeabi_uldivmod" error.
These changes were manually tested on a local build.

### CODE REVIEW

**Comment by mlevy94** [comment]
who is adding the /etc/modules.d/ipt-ndpi file? We can just modify it instead of modifying the source code.

**Comment by akaryakinx** [comment]
It's the AutoProbe command in the package Makefile that adds the module to /etc/modules.d. People modify the command e.g. like this: https://dev.archive.openwrt.org/ticket/2359.html#comment:8

**Review by mlevy94 — APPROVED** [review]
alright, lets go with your method.

**Review by BroderickJack — APPROVED** [review]

**Comment by akaryakinx** [comment]
Actually, there is an option to add module parameters in kernel.mk (MODPARAMS). I will update after testing it out.

**Pull request merged**
